import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "./components/footer";
import Header from "./components/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html
        lang="pt-BR"
        className={`${inter.className} h-full scroll-smooth antialiased`}
      >
        <body className="flex h-full flex-col">
          <Header />
          <main className="grow">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
