export const vipList: HomeCardProps[] = [
  {
    id: 1,
    title: "Vip Nexus",
    description: "Garanta esse vip e receba benefícios exclusivos por 30 dias!",
    duration: 30,
    tag: "Nexus",
    imageUrl: "/vipnexus.jpg",
  },
  {
    id: 2,
    title: "Vip Estelar",
    description: "Garanta esse vip e receba benefícios exclusivos por 30 dias!",
    duration: 30,
    tag: "Estelar",
    imageUrl: "/vipestelar.jpg",
  },
  {
    id: 3,
    title: "Vip Pulse",
    description: "Garanta esse vip e receba benefícios exclusivos por 30 dias!",
    duration: 30,
    tag: "Pulse",
    imageUrl: "/vippulse.jpg",
  },
  {
    id: 4,
    title: "Vip Nexus",
    description: "Garanta esse vip e receba benefícios exclusivos por 15 dias!",
    duration: 15,
    tag: "Nexus",
    imageUrl: "/vipnexus.jpg",
  },
  {
    id: 5,
    title: "Vip Estelar",
    description: "Garanta esse vip e receba benefícios exclusivos por 15 dias!",
    duration: 15,
    tag: "Estelar",
    imageUrl: "/vipestelar.jpg",
  },
  {
    id: 6,
    title: "Vip Pulse",
    description: "Garanta esse vip e receba benefícios exclusivos por 15 dias!",
    duration: 15,
    tag: "Pulse",
    imageUrl: "/vippulse.jpg",
  },
  {
    id: 7,
    title: "Vip Nexus",
    description: "Garanta esse vip e receba benefícios exclusivos por 7 dias!",
    duration: 7,
    tag: "Nexus",
    imageUrl: "/vipnexus.jpg",
  },
  {
    id: 8,
    title: "Vip Estelar",
    description: "Garanta esse vip e receba benefícios exclusivos por 7 dias!",
    duration: 7,
    tag: "Estelar",
    imageUrl: "/vipestelar.jpg",
  },
  {
    id: 9,
    title: "Vip Pulse",
    description: "Garanta esse vip e receba benefícios exclusivos por 7 dias!",
    duration: 7,
    tag: "Pulse",
    imageUrl: "/vippulse.jpg",
  },
];
